[build]
  command = "npm run frontend -- --mode=production"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--omit=dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
